apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev-workspace
servers: 1
agents: 1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 6443:6443
    nodeFilters:
      - server:0
volumes:
  - volume: /Users/shuk/projects/env_setup:/workspace
    nodeFilters:
      - all
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
